### ISSUE TITLE
Hex vs decimal adresses

### ISSUE THREAD

**Issue by francisdb** [tomlogic/pinmame-nvram-maps#33]
I think it would be best to standardize to one notation. This makes comparing addresses between files simpler.
Decimal values can probably be read more efficient.

**Comment by tomlogic** [comment]
My preference is to work in hex, but we should probably standardize on decimal.  My method of storing hex values in strings is non-standard for JSON and requires more work to convert.

I'll throw together some Python code to do the conversion and add it to my current branch.  Perhaps it should become the standard tool for formatting the JSON files instead of `jq`.  In addition to the pretty-print format and converting hex offsets, I can get rid of the deprecated `packed` attribute.

**Comment by francisdb** [comment]
So if hex is kept I prefer to enforce a standard: `"12AB"` or `"12ab"`

**Comment by tomlogic** [comment]
Addressed by [feature/standardize-json-formatting](../tree/feature/standardize-json-formatting).

For scale, I'd prefer to keep the original datatype.  Most of the time it's an integer, but on Doctor Who it's 0.1 to support fractional playfield multipliers.

**Comment by francisdb** [comment]
Wonder if we'll ever see anything else than 0.1, 1 , 10, 100.
To avoid int/float a decimal shift int could also represent this.
